### ISSUE TITLE
递归引用问题

### ISSUE THREAD

**Issue by ZhaoUjun** [gintamamadao/schema-verify#1]
目前支持自身引用自身吗？比如，有个Object下面的field的类型是是自身，这种情况怎么处理？

**Comment by gintamamadao** [comment]
@ZhaoUjun 因为校验的时候，只是针对设置的规则进行递归，并不会对目标数据进行递归校验，所以只要规则没有循环引用的话都不会有问题，但如果要校验某个字段是否是循环引用，现在还做不到
